/*
 Navicat Premium Data Transfer

 Source Server         : tbo_cpanel
 Source Server Type    : MySQL
 Source Server Version : 100327
 Source Host           : 153.92.10.74:3306
 Source Schema         : u5030462_tbo

 Target Server Type    : MySQL
 Target Server Version : 100327
 File Encoding         : 65001

 Date: 30/12/2020 09:54:23
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for cnf
-- ----------------------------
DROP TABLE IF EXISTS `cnf`;
CREATE TABLE `cnf`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `head` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `body` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 529 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of cnf
-- ----------------------------
INSERT INTO `cnf` VALUES (1, 'K', 'K O');
INSERT INTO `cnf` VALUES (2, 'K', 'K Ket');
INSERT INTO `cnf` VALUES (3, 'K', 'S P');
INSERT INTO `cnf` VALUES (4, 'S', 'FN Nama');
INSERT INTO `cnf` VALUES (5, 'FN', 'Gubernur');
INSERT INTO `cnf` VALUES (6, 'Nama', 'Koster');
INSERT INTO `cnf` VALUES (7, 'P', 'FA Kj');
INSERT INTO `cnf` VALUES (8, 'FA', 'taler');
INSERT INTO `cnf` VALUES (9, 'Kj', 'ngaturang');
INSERT INTO `cnf` VALUES (10, 'O', 'suksmaning manah');
INSERT INTO `cnf` VALUES (11, 'Ket', 'Pn FN');
INSERT INTO `cnf` VALUES (12, 'Pn', 'Majeng');
INSERT INTO `cnf` VALUES (13, 'Bd', 'fraksi-fraksi');
INSERT INTO `cnf` VALUES (14, 'FN', 'DPRD Provinsi Bali');
INSERT INTO `cnf` VALUES (15, 'K', 'K Pel');
INSERT INTO `cnf` VALUES (16, 'S', 'Putri Koster');
INSERT INTO `cnf` VALUES (17, 'P', 'FA Pr');
INSERT INTO `cnf` VALUES (18, 'Pr', 'nangiang');
INSERT INTO `cnf` VALUES (20, 'Pel', 'FA Bd');
INSERT INTO `cnf` VALUES (21, 'FA', 'nincapan');
INSERT INTO `cnf` VALUES (23, 'FN', 'Pasar');
INSERT INTO `cnf` VALUES (24, 'Nama', 'Gotong Royong Pangan Krama Bali');
INSERT INTO `cnf` VALUES (25, 'Kj', 'kalaksanayang');
INSERT INTO `cnf` VALUES (26, 'Ket', 'Ps FP');
INSERT INTO `cnf` VALUES (27, 'Pn', 'ring');
INSERT INTO `cnf` VALUES (28, 'FP', 'hari kerja');
INSERT INTO `cnf` VALUES (29, 'S', 'Pembeli');
INSERT INTO `cnf` VALUES (30, 'P', 'ngemastikayang');
INSERT INTO `cnf` VALUES (31, 'O', 'Bd FA');
INSERT INTO `cnf` VALUES (32, 'Bd', 'angga');
INSERT INTO `cnf` VALUES (33, 'FA', 'kenak');
INSERT INTO `cnf` VALUES (34, 'S', 'FN Gt');
INSERT INTO `cnf` VALUES (35, 'S', 'Makehan perajin');
INSERT INTO `cnf` VALUES (36, 'P', 'ngaryanin');
INSERT INTO `cnf` VALUES (37, 'O', 'FN Pr');
INSERT INTO `cnf` VALUES (38, 'FN', 'karya');
INSERT INTO `cnf` VALUES (39, 'Pr', 'sane');
INSERT INTO `cnf` VALUES (40, 'O', 'O Kj');
INSERT INTO `cnf` VALUES (41, 'Kj', 'malakar');
INSERT INTO `cnf` VALUES (42, 'O', 'O Pn');
INSERT INTO `cnf` VALUES (43, 'Pn', 'antuk');
INSERT INTO `cnf` VALUES (44, 'O', 'O Bd');
INSERT INTO `cnf` VALUES (45, 'Bd', 'kayu');
INSERT INTO `cnf` VALUES (46, 'S', 'Pandemi COVID-19');
INSERT INTO `cnf` VALUES (47, 'P', 'FA FN');
INSERT INTO `cnf` VALUES (48, 'Ps', 'banget');
INSERT INTO `cnf` VALUES (49, 'FN', 'mawesana');
INSERT INTO `cnf` VALUES (50, 'FA', 'Ps');
INSERT INTO `cnf` VALUES (51, 'FN', 'FN FN');
INSERT INTO `cnf` VALUES (52, 'FN', 'ekonomi');
INSERT INTO `cnf` VALUES (53, 'FN', 'Nama');
INSERT INTO `cnf` VALUES (54, 'Nama', 'Bali');
INSERT INTO `cnf` VALUES (55, 'P', 'FA Bd');
INSERT INTO `cnf` VALUES (56, 'FA', 'taler tan');
INSERT INTO `cnf` VALUES (57, 'Bd', 'surud-surud');
INSERT INTO `cnf` VALUES (58, 'P', 'P Kj');
INSERT INTO `cnf` VALUES (59, 'Kj', 'maosang');
INSERT INTO `cnf` VALUES (60, 'O', 'FN Pn');
INSERT INTO `cnf` VALUES (61, 'FN', 'parindikane');
INSERT INTO `cnf` VALUES (62, 'Ps', 'puniki');
INSERT INTO `cnf` VALUES (63, 'Pel', 'FP Nama');
INSERT INTO `cnf` VALUES (64, 'FP', 'sareng');
INSERT INTO `cnf` VALUES (65, 'Nama', 'Manteri Pariwisata');
INSERT INTO `cnf` VALUES (67, 'P', 'Ps FV');
INSERT INTO `cnf` VALUES (68, 'Ps', 'prasida');
INSERT INTO `cnf` VALUES (69, 'FV', 'makarya');
INSERT INTO `cnf` VALUES (70, 'O', 'Bil FN');
INSERT INTO `cnf` VALUES (71, 'Bil', '15');
INSERT INTO `cnf` VALUES (72, 'FN', 'porsi abon pindang');
INSERT INTO `cnf` VALUES (73, 'S', 'FN Pn');
INSERT INTO `cnf` VALUES (74, 'FN', 'Bd FN');
INSERT INTO `cnf` VALUES (75, 'Bd', 'usaha');
INSERT INTO `cnf` VALUES (76, 'FN', 'kuliner');
INSERT INTO `cnf` VALUES (78, 'Ket', 'Ps Bd');
INSERT INTO `cnf` VALUES (79, 'Bd', 'jeronnyane');
INSERT INTO `cnf` VALUES (80, 'FP', 'Bd Nama');
INSERT INTO `cnf` VALUES (81, 'S', 'Titiang');
INSERT INTO `cnf` VALUES (82, 'S', 'Luh Sari');
INSERT INTO `cnf` VALUES (84, 'P', 'medagang');
INSERT INTO `cnf` VALUES (85, 'P', 'ngadep');
INSERT INTO `cnf` VALUES (86, 'P', 'ngadepang');
INSERT INTO `cnf` VALUES (87, 'P', 'meliang');
INSERT INTO `cnf` VALUES (88, 'O', 'jukut');
INSERT INTO `cnf` VALUES (89, 'O', 'jaja');
INSERT INTO `cnf` VALUES (90, 'O', 'meme');
INSERT INTO `cnf` VALUES (91, 'O', 'adine');
INSERT INTO `cnf` VALUES (92, 'Pel', 'jukut');
INSERT INTO `cnf` VALUES (93, 'Pel', 'buku');
INSERT INTO `cnf` VALUES (94, 'Pn', 'di');
INSERT INTO `cnf` VALUES (95, 'Bd', 'peken');
INSERT INTO `cnf` VALUES (96, 'FN', 'Toko Gramedia');
INSERT INTO `cnf` VALUES (97, 'Nama', 'Klungkung');
INSERT INTO `cnf` VALUES (98, 'S', 'Gt FN');
INSERT INTO `cnf` VALUES (99, 'Gt', 'Para');
INSERT INTO `cnf` VALUES (100, 'FN', 'yowana');
INSERT INTO `cnf` VALUES (101, 'P', 'Kj FN');
INSERT INTO `cnf` VALUES (102, 'Kj', 'pinaka');
INSERT INTO `cnf` VALUES (103, 'FN', 'embas');
INSERT INTO `cnf` VALUES (104, 'Ket', 'Ps Nama');
INSERT INTO `cnf` VALUES (105, 'Ket', 'Pn FP');
INSERT INTO `cnf` VALUES (106, 'Nama', 'Galungan');
INSERT INTO `cnf` VALUES (107, 'FN', 'Dina mabasa');
INSERT INTO `cnf` VALUES (108, 'P', 'katureksain');
INSERT INTO `cnf` VALUES (109, 'Pel', 'Ps Pel');
INSERT INTO `cnf` VALUES (110, 'Ps', 'dahat');
INSERT INTO `cnf` VALUES (111, 'Pel', 'Sf Kj');
INSERT INTO `cnf` VALUES (112, 'Sf', 'becik');
INSERT INTO `cnf` VALUES (114, 'S', 'Ps FA');
INSERT INTO `cnf` VALUES (115, 'Ps', 'Sane');
INSERT INTO `cnf` VALUES (116, 'FA', 'Akeh');
INSERT INTO `cnf` VALUES (117, 'P', 'wantah');
INSERT INTO `cnf` VALUES (118, 'FV', 'nganggen');
INSERT INTO `cnf` VALUES (119, 'O', 'basa campuran');
INSERT INTO `cnf` VALUES (120, 'S', 'Bd FN');
INSERT INTO `cnf` VALUES (121, 'Bd', 'Pemerintah');
INSERT INTO `cnf` VALUES (123, 'P', 'ngamargiang');
INSERT INTO `cnf` VALUES (124, 'O', 'Bd FN');
INSERT INTO `cnf` VALUES (126, 'FN', 'Nama Kt');
INSERT INTO `cnf` VALUES (127, 'Nama', 'Bulan Bahasa Bali');
INSERT INTO `cnf` VALUES (128, 'Kt', 'warsa 2020');
INSERT INTO `cnf` VALUES (129, 'K', 'Pel Ket');
INSERT INTO `cnf` VALUES (130, 'S', 'Dane');
INSERT INTO `cnf` VALUES (131, 'P', 'Ps FN');
INSERT INTO `cnf` VALUES (132, 'Ps', 'taler');
INSERT INTO `cnf` VALUES (133, 'FN', 'mapangapti');
INSERT INTO `cnf` VALUES (134, 'Pel', 'Pn FN');
INSERT INTO `cnf` VALUES (135, 'FN', 'Pr FN');
INSERT INTO `cnf` VALUES (136, 'Pr', 'miwah');
INSERT INTO `cnf` VALUES (137, 'FN', 'para yowana');
INSERT INTO `cnf` VALUES (138, 'Ket', 'Pn Nama');
INSERT INTO `cnf` VALUES (139, 'FN', 'desa Beraban');
INSERT INTO `cnf` VALUES (140, 'Ket', 'Pn Bd');
INSERT INTO `cnf` VALUES (141, 'FV', 'mapinunas');
INSERT INTO `cnf` VALUES (142, 'Bd', 'tenaga penyuluh');
INSERT INTO `cnf` VALUES (143, 'FN', 'Bd Nama');
INSERT INTO `cnf` VALUES (144, 'Bd', 'Bahasa Bali');
INSERT INTO `cnf` VALUES (145, 'Nama', 'Desa Beraban');
INSERT INTO `cnf` VALUES (146, 'S', 'Dewa Indra');
INSERT INTO `cnf` VALUES (147, 'P', 'ngaptiang');
INSERT INTO `cnf` VALUES (148, 'Bd', 'krama');
INSERT INTO `cnf` VALUES (149, 'FN', 'Nama Ps');
INSERT INTO `cnf` VALUES (150, 'Ps', 'Makasami');
INSERT INTO `cnf` VALUES (151, 'P', 'negesan');
INSERT INTO `cnf` VALUES (152, 'Pel', 'Ps FN');
INSERT INTO `cnf` VALUES (153, 'Ps', 'mangda');
INSERT INTO `cnf` VALUES (154, 'Bd', 'kramane');
INSERT INTO `cnf` VALUES (155, 'FN', 'Kj Nama');
INSERT INTO `cnf` VALUES (156, 'Kj', 'masan');
INSERT INTO `cnf` VALUES (157, 'Nama', 'Bendera Merah Putih');
INSERT INTO `cnf` VALUES (158, 'S', 'FN Ps');
INSERT INTO `cnf` VALUES (159, 'FN', 'Yayasan');
INSERT INTO `cnf` VALUES (160, 'O', 'FN Ps');
INSERT INTO `cnf` VALUES (161, 'Ps', 'punika');
INSERT INTO `cnf` VALUES (162, 'P', 'nedungin');
INSERT INTO `cnf` VALUES (163, 'Bil', '16');
INSERT INTO `cnf` VALUES (164, 'FN', 'satuan pendidikan kerjasama');
INSERT INTO `cnf` VALUES (165, 'FN', 'Satuan pendidikan kerjasama');
INSERT INTO `cnf` VALUES (166, 'Bd', 'sistem ajah-ajah');
INSERT INTO `cnf` VALUES (167, 'FN', 'Ps');
INSERT INTO `cnf` VALUES (168, 'Ps', 'presida mewali sekadi dumun');
INSERT INTO `cnf` VALUES (169, 'K', 'O Pel');
INSERT INTO `cnf` VALUES (170, 'S', 'Putri Koster');
INSERT INTO `cnf` VALUES (171, 'P', 'nangiang');
INSERT INTO `cnf` VALUES (172, 'O', 'UMKM');
INSERT INTO `cnf` VALUES (173, 'Ps', 'setata');
INSERT INTO `cnf` VALUES (174, 'FN', 'angga');
INSERT INTO `cnf` VALUES (175, 'K', 'O Ket');
INSERT INTO `cnf` VALUES (176, 'S', 'UMKM');
INSERT INTO `cnf` VALUES (177, 'Ps', 'tetep');
INSERT INTO `cnf` VALUES (178, 'FV', 'nguripan');
INSERT INTO `cnf` VALUES (179, 'O', 'perekonomian iraga');
INSERT INTO `cnf` VALUES (180, 'FN', 'masang gering');
INSERT INTO `cnf` VALUES (182, 'P', 'nyihnahang');
INSERT INTO `cnf` VALUES (183, 'Bd', 'kauratiang');
INSERT INTO `cnf` VALUES (184, 'FN', 'Ps FN');
INSERT INTO `cnf` VALUES (185, 'Ps', 'sane');
INSERT INTO `cnf` VALUES (186, 'FN', 'mageng');
INSERT INTO `cnf` VALUES (187, 'Ps', 'majeng');
INSERT INTO `cnf` VALUES (188, 'FN', 'kawentenan UMKM');
INSERT INTO `cnf` VALUES (189, 'S', 'Bali');
INSERT INTO `cnf` VALUES (190, 'P', 'medue');
INSERT INTO `cnf` VALUES (191, 'O', 'kaluwihan');
INSERT INTO `cnf` VALUES (192, 'Ps', 'inggih punika');
INSERT INTO `cnf` VALUES (193, 'Bd', 'jiwa');
INSERT INTO `cnf` VALUES (194, 'Bd', 'seni');
INSERT INTO `cnf` VALUES (195, 'FN', 'Ps Bd');
INSERT INTO `cnf` VALUES (196, 'Bd', 'kentel');
INSERT INTO `cnf` VALUES (197, 'P', 'Pn Nama');
INSERT INTO `cnf` VALUES (198, 'S', 'Ps FN');
INSERT INTO `cnf` VALUES (199, 'FN', 'Bd Ps');
INSERT INTO `cnf` VALUES (201, 'Ps', 'pisan');
INSERT INTO `cnf` VALUES (202, 'O', 'Bd Ps');
INSERT INTO `cnf` VALUES (203, 'Bd', 'acara');
INSERT INTO `cnf` VALUES (204, 'S', 'Wisatawan');
INSERT INTO `cnf` VALUES (205, 'Ps', 'sampun');
INSERT INTO `cnf` VALUES (206, 'FV', 'Kj Ps');
INSERT INTO `cnf` VALUES (207, 'Kj', 'mejanten');
INSERT INTO `cnf` VALUES (208, 'Ps', 'nenten uning');
INSERT INTO `cnf` VALUES (209, 'Bd', 'geguat');
INSERT INTO `cnf` VALUES (210, 'FN', 'Kj FP');
INSERT INTO `cnf` VALUES (211, 'Kj', 'ngranjing');
INSERT INTO `cnf` VALUES (212, 'FP', 'Pn Kt');
INSERT INTO `cnf` VALUES (213, 'Pn', 'ka');
INSERT INTO `cnf` VALUES (214, 'Kt', 'pura');
INSERT INTO `cnf` VALUES (215, 'S', 'Bil FN');
INSERT INTO `cnf` VALUES (216, 'S', 'Nama Pn');
INSERT INTO `cnf` VALUES (217, 'S', 'Bd Nama');
INSERT INTO `cnf` VALUES (218, 'P', 'Kt FV');
INSERT INTO `cnf` VALUES (219, 'P', 'Pr FV');
INSERT INTO `cnf` VALUES (220, 'P', 'Kj FV');
INSERT INTO `cnf` VALUES (221, 'P', 'Sf FV');
INSERT INTO `cnf` VALUES (222, 'P', 'Ps Nama');
INSERT INTO `cnf` VALUES (223, 'O', 'Ps FA');
INSERT INTO `cnf` VALUES (224, 'O', 'Pr FN');
INSERT INTO `cnf` VALUES (225, 'Pel', 'Kj FN');
INSERT INTO `cnf` VALUES (226, 'Pel', 'Bd FN');
INSERT INTO `cnf` VALUES (227, 'Pel', 'Pr FA');
INSERT INTO `cnf` VALUES (228, 'Pel', 'Sf Nama');
INSERT INTO `cnf` VALUES (229, 'Pel', 'FN Pn');
INSERT INTO `cnf` VALUES (230, 'FN', 'Bil FN');
INSERT INTO `cnf` VALUES (231, 'FN', 'Nama Pn');
INSERT INTO `cnf` VALUES (232, 'FN', 'FN Pn');
INSERT INTO `cnf` VALUES (233, 'FN', 'FN Kj');
INSERT INTO `cnf` VALUES (234, 'FN', 'FN Nama');
INSERT INTO `cnf` VALUES (235, 'FN', 'Bd FA');
INSERT INTO `cnf` VALUES (236, 'FN', 'FN Bil');
INSERT INTO `cnf` VALUES (237, 'FN', 'FN Ps');
INSERT INTO `cnf` VALUES (238, 'FV', 'Sf FV');
INSERT INTO `cnf` VALUES (239, 'FV', 'Pr FV');
INSERT INTO `cnf` VALUES (240, 'FV', 'Ps FV');
INSERT INTO `cnf` VALUES (241, 'FV', 'Kj FV');
INSERT INTO `cnf` VALUES (242, 'FP', 'Bd FP');
INSERT INTO `cnf` VALUES (243, 'FP', 'Kj FN');
INSERT INTO `cnf` VALUES (244, 'FA', 'Kj FA');
INSERT INTO `cnf` VALUES (245, 'FA', 'Bd FA');
INSERT INTO `cnf` VALUES (246, 'FA', 'Pn FA');
INSERT INTO `cnf` VALUES (247, 'FA', 'Ps FA');
INSERT INTO `cnf` VALUES (248, 'FA', 'Sf Ps');
INSERT INTO `cnf` VALUES (249, 'S', 'Gubernur Koster');
INSERT INTO `cnf` VALUES (250, 'S', 'Astawa');
INSERT INTO `cnf` VALUES (251, 'S', 'I Gede Putra Ariawan');
INSERT INTO `cnf` VALUES (252, 'S', 'Dosen Bahasa Lan Sastra Bali Unud');
INSERT INTO `cnf` VALUES (253, 'S', 'Pemedek');
INSERT INTO `cnf` VALUES (254, 'S', 'Kadek Suprapta Meranggi');
INSERT INTO `cnf` VALUES (255, 'P', 'nuturang');
INSERT INTO `cnf` VALUES (256, 'P', 'kaloktah');
INSERT INTO `cnf` VALUES (257, 'P', 'ngelaksanayang');
INSERT INTO `cnf` VALUES (258, 'O', 'pulah palih');
INSERT INTO `cnf` VALUES (259, 'FN', 'positif');
INSERT INTO `cnf` VALUES (260, 'FN', 'Krama');
INSERT INTO `cnf` VALUES (261, 'FN', 'rumah sakit');
INSERT INTO `cnf` VALUES (262, 'FN', 'kabencana');
INSERT INTO `cnf` VALUES (263, 'FN', 'pemargi');
INSERT INTO `cnf` VALUES (264, 'FN', 'pariwisata');
INSERT INTO `cnf` VALUES (265, 'FN', 'pura');
INSERT INTO `cnf` VALUES (266, 'FN', 'Negara');
INSERT INTO `cnf` VALUES (267, 'FN', 'terorisme');
INSERT INTO `cnf` VALUES (268, 'FN', 'manah');
INSERT INTO `cnf` VALUES (270, 'FN', 'diri');
INSERT INTO `cnf` VALUES (271, 'FN', 'dane');
INSERT INTO `cnf` VALUES (272, 'FN', 'Bali');
INSERT INTO `cnf` VALUES (273, 'FN', 'pacentokan');
INSERT INTO `cnf` VALUES (274, 'FN', 'titi');
INSERT INTO `cnf` VALUES (275, 'FN', 'angon');
INSERT INTO `cnf` VALUES (276, 'FN', 'pengalgal');
INSERT INTO `cnf` VALUES (277, 'FN', 'acara');
INSERT INTO `cnf` VALUES (278, 'FN', 'baga');
INSERT INTO `cnf` VALUES (279, 'FN', 'bengkel');
INSERT INTO `cnf` VALUES (280, 'FN', 'utsaha');
INSERT INTO `cnf` VALUES (281, 'FN', 'pandemi');
INSERT INTO `cnf` VALUES (282, 'FN', 'kramane');
INSERT INTO `cnf` VALUES (283, 'FV', 'katambanin');
INSERT INTO `cnf` VALUES (285, 'FV', 'becik');
INSERT INTO `cnf` VALUES (286, 'FV', 'ngambil');
INSERT INTO `cnf` VALUES (288, 'FV', 'nyumbungan');
INSERT INTO `cnf` VALUES (289, 'FV', 'kaaptiang');
INSERT INTO `cnf` VALUES (290, 'FV', 'katangarin');
INSERT INTO `cnf` VALUES (291, 'FV', 'nyaga');
INSERT INTO `cnf` VALUES (292, 'FV', 'ngaturang');
INSERT INTO `cnf` VALUES (293, 'FV', 'kaucap');
INSERT INTO `cnf` VALUES (294, 'FV', 'ngelaksanang');
INSERT INTO `cnf` VALUES (296, 'FV', 'ngelaksanayang');
INSERT INTO `cnf` VALUES (297, 'FV', 'memargi');
INSERT INTO `cnf` VALUES (298, 'FV', 'nyontoang');
INSERT INTO `cnf` VALUES (299, 'FV', 'kauningin');
INSERT INTO `cnf` VALUES (300, 'FA', 'satia');
INSERT INTO `cnf` VALUES (301, 'FA', 'becik');
INSERT INTO `cnf` VALUES (302, 'FA', 'virtual');
INSERT INTO `cnf` VALUES (303, 'Bd', 'Pasien');
INSERT INTO `cnf` VALUES (304, 'Bd', 'pulah palih');
INSERT INTO `cnf` VALUES (305, 'Bd', 'konferensi');
INSERT INTO `cnf` VALUES (306, 'Bd', 'industri');
INSERT INTO `cnf` VALUES (307, 'Bd', 'pariwisata');
INSERT INTO `cnf` VALUES (308, 'Bd', 'karesikan');
INSERT INTO `cnf` VALUES (309, 'Bd', 'kasucian');
INSERT INTO `cnf` VALUES (310, 'Bd', 'seseleh');
INSERT INTO `cnf` VALUES (311, 'Bd', 'dura');
INSERT INTO `cnf` VALUES (312, 'Bd', 'Aksi');
INSERT INTO `cnf` VALUES (313, 'Bd', 'suksmaning');
INSERT INTO `cnf` VALUES (314, 'Bd', 'Anak');
INSERT INTO `cnf` VALUES (315, 'Bd', 'genah');
INSERT INTO `cnf` VALUES (316, 'Bd', 'sesuduk');
INSERT INTO `cnf` VALUES (317, 'Bd', 'Wakil Gubernur');
INSERT INTO `cnf` VALUES (318, 'Bd', 'layangan');
INSERT INTO `cnf` VALUES (319, 'Bd', 'Pacentokan');
INSERT INTO `cnf` VALUES (320, 'Bd', 'rare');
INSERT INTO `cnf` VALUES (321, 'Bd', 'baga');
INSERT INTO `cnf` VALUES (322, 'Bd', 'pemilet');
INSERT INTO `cnf` VALUES (323, 'Bd', 'Kawentenang');
INSERT INTO `cnf` VALUES (324, 'Kt', 'kantun');
INSERT INTO `cnf` VALUES (325, 'Kt', 'durung');
INSERT INTO `cnf` VALUES (326, 'Kt', 'dahat');
INSERT INTO `cnf` VALUES (327, 'Kj', 'nyanggra');
INSERT INTO `cnf` VALUES (328, 'Kj', 'mapikayun');
INSERT INTO `cnf` VALUES (329, 'Kj', 'nindihin');
INSERT INTO `cnf` VALUES (330, 'Kj', 'kaaptiyang');
INSERT INTO `cnf` VALUES (331, 'Kj', 'nyarengin');
INSERT INTO `cnf` VALUES (332, 'Kj', 'ngicen');
INSERT INTO `cnf` VALUES (333, 'Kj', 'mekarya');
INSERT INTO `cnf` VALUES (334, 'Kj', 'mungkah');
INSERT INTO `cnf` VALUES (335, 'Kj', 'dados');
INSERT INTO `cnf` VALUES (336, 'Sf', 'urati');
INSERT INTO `cnf` VALUES (337, 'Sf', 'patut');
INSERT INTO `cnf` VALUES (338, 'Sf', 'negatif');
INSERT INTO `cnf` VALUES (339, 'Sf', 'virtual');
INSERT INTO `cnf` VALUES (340, 'Pn', 'punika');
INSERT INTO `cnf` VALUES (341, 'Pn', 'pungkuran');
INSERT INTO `cnf` VALUES (342, 'Pn', 'puniki');
INSERT INTO `cnf` VALUES (343, 'Pn', 'sane');
INSERT INTO `cnf` VALUES (344, 'Ps', 'indik');
INSERT INTO `cnf` VALUES (345, 'Ps', 'naler');
INSERT INTO `cnf` VALUES (346, 'Ps', 'pinaka');
INSERT INTO `cnf` VALUES (347, 'Ps', 'sami');
INSERT INTO `cnf` VALUES (348, 'Ps', 'para');
INSERT INTO `cnf` VALUES (349, 'Ps', 'raris');
INSERT INTO `cnf` VALUES (350, 'Ps', 'kantun');
INSERT INTO `cnf` VALUES (351, 'Pr', 'mangda');
INSERT INTO `cnf` VALUES (352, 'Pr', 'lan');
INSERT INTO `cnf` VALUES (353, 'Pr', 'taler');
INSERT INTO `cnf` VALUES (354, 'Pr', 'wiadin');
INSERT INTO `cnf` VALUES (355, 'Pr', 'olih');
INSERT INTO `cnf` VALUES (356, 'Bil', '11');
INSERT INTO `cnf` VALUES (357, 'Bil', 'kalih');
INSERT INTO `cnf` VALUES (358, 'Nama', 'Ngewacen Cerpen');
INSERT INTO `cnf` VALUES (359, 'Nama', 'DPRD Provinsi Bali');
INSERT INTO `cnf` VALUES (360, 'Nama', 'Covid-19');
INSERT INTO `cnf` VALUES (361, 'Nama', 'Sekretaris Daerah Provinsi Bali');
INSERT INTO `cnf` VALUES (362, 'Nama', 'PMI');
INSERT INTO `cnf` VALUES (363, 'Nama', 'Tjokorda Oka Artha Ardhana Sukawati');
INSERT INTO `cnf` VALUES (364, 'Nama', 'Guru Besar ISI Denpasar');
INSERT INTO `cnf` VALUES (365, 'Nama', 'PBMB');
INSERT INTO `cnf` VALUES (366, 'FN', 'pasien');
INSERT INTO `cnf` VALUES (367, 'P', 'maweweh');
INSERT INTO `cnf` VALUES (368, 'Pel', 'Bil Ps');
INSERT INTO `cnf` VALUES (369, 'Ps', 'diri');
INSERT INTO `cnf` VALUES (370, 'Ket', 'Kt FN');
INSERT INTO `cnf` VALUES (371, 'Kt', 'kantos');
INSERT INTO `cnf` VALUES (372, 'Nama', 'Respati');
INSERT INTO `cnf` VALUES (374, 'Ps', 'makasami');
INSERT INTO `cnf` VALUES (375, 'O', 'swadharma');
INSERT INTO `cnf` VALUES (376, 'P', 'nyihnayang');
INSERT INTO `cnf` VALUES (502, 'O', 'kramane');
INSERT INTO `cnf` VALUES (503, 'FN', 'lanang');
INSERT INTO `cnf` VALUES (504, 'FV', 'lantang');
INSERT INTO `cnf` VALUES (505, 'FV', 'sumeken');
INSERT INTO `cnf` VALUES (506, 'Bd', 'sumeken');
INSERT INTO `cnf` VALUES (507, 'S', 'pamikarya');
INSERT INTO `cnf` VALUES (508, 'Kj', 'keni');
INSERT INTO `cnf` VALUES (509, 'Pel', 'PHK');
INSERT INTO `cnf` VALUES (510, 'Bd', 'parikrama HATINYA PKK');
INSERT INTO `cnf` VALUES (511, 'S', 'Industri pariwisata');
INSERT INTO `cnf` VALUES (512, 'S', 'Ibu Jero');
INSERT INTO `cnf` VALUES (513, 'S', 'Ia');
INSERT INTO `cnf` VALUES (514, 'P', 'palemahan');
INSERT INTO `cnf` VALUES (515, 'FN', 'parikrama');
INSERT INTO `cnf` VALUES (517, 'FN', 'Menteri Pariwisata');
INSERT INTO `cnf` VALUES (518, 'FN', 'Utsaha');
INSERT INTO `cnf` VALUES (520, 'FV', 'nyarengin');
INSERT INTO `cnf` VALUES (521, 'Kj', 'majanten');
INSERT INTO `cnf` VALUES (522, 'FA', 'akeh');
INSERT INTO `cnf` VALUES (523, 'Bd', 'alit-alit');
INSERT INTO `cnf` VALUES (524, 'FN', 'Desa Beraban');
INSERT INTO `cnf` VALUES (525, 'Ps', 'mecikang');
INSERT INTO `cnf` VALUES (526, 'Nama', 'gering');
INSERT INTO `cnf` VALUES (527, 'O', 'memene');
INSERT INTO `cnf` VALUES (528, 'Bil', 'Kalih');

SET FOREIGN_KEY_CHECKS = 1;
